baseURL = "https://pybcn.org"
languageCode = "en-us"
title = "PyBCN - The Barcelona Python Association"
theme = "pybcn_theme"
googleAnalytics = "UA-152706496-1"

[markup.goldmark.renderer]
unsafe=true

[params]
    main_contact_name = "PyBCN Organizers"
    main_contact_email = "pybcn@googlegroups.com"
    short_name = "PyBCN"
    extended_name = "The Barcelona Python Association"

    main_contact_name_pyladies = "PyLadiesBCN Organizers"
    main_contact_email_pyladies = "pyladies-bcn@googlegroups.com"

    [params.social_items]
        [params.social_items.twitter]
            icon = "fab fa-twitter-square fa-2x"
            link = "https://twitter.com/pybcn"
        [params.social_items.youtube]
            link = "https://www.youtube.com/channel/UCEhI2CfdT5--TYq47K4en4A/videos"
            icon = "fab fa-youtube-square fa-2x"
        [params.social_items.meetup]
            link = "https://www.meetup.com/python-barcelona/"
            icon = "fab fa-meetup fa-2x"
        [params.social_items.github]
            link = "https://github.com/pybcn"
            icon = "fab fa-github fa-2x"
        [params.social_items.linkedin]
            link = "https://www.linkedin.com/company/14840728"
            icon = "fab fa-linkedin fa-2x"
        [params.social_items.slack]
            link = "https://pybcn.slack.com"
            icon = "fab fa-slack fa-2x"

    [params.social_items_pyladies]
        [params.social_items_pyladies.twitter]
            icon = "fab fa-twitter-square fa-2x"
            link = "https://twitter.com/PyLadiesBCN"
        [params.social_items_pyladies.meetup]
            link = "https://www.meetup.com/PyLadies-BCN"
            icon = "fab fa-meetup fa-2x"
        [params.social_items_pyladies.github]
            link = "https://github.com/pyladies-bcn"
            icon = "fab fa-github fa-2x"

