image: archlinux
packages:
  - nodejs-lts-erbium
  - npm
sources:
  - https://git.sr.ht/~alanorth/hugo-theme-bootstrap4-blog
tasks:
  - setup: |
      id
      node -v
      cd pybcn_theme
      npm install 
  - test: |
      cd pybcn_theme
      npm run build
